/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import java.util.ArrayList;
import lapr.project.controller.BestPathController;
import lapr.project.model.Junction;
import lapr.project.model.Project;
import lapr.project.model.RoadNetwork;
import lapr.project.model.Vehicle;

/**
 *
 * @author rgcar
 */
public class BestPathUI extends javax.swing.JFrame {
      public static final long serialVersionUID = 1L;
      private Project project;
      private Vehicle v;
      private Junction j1, j2;
      private ArrayList<String> vehicleList;
      private ArrayList<String> path;
      private double load = 1000.0;
      

    /**
     * Creates new form BestPathUI
     * @param project
     */
    public BestPathUI(Project project) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.project = project;
        activeProjectTF.setText(project.getName());
        populateVehicleComboBox();
        populateInitPointComboBox();
        populateEndPointComboBox();
        
    }
    
    private void populateVehicleComboBox() {
        BestPathController bpc = new BestPathController(this.project);
        vehicleList = bpc.getComboBoxVehicleList(this.project);
        String[] array = vehicleList.toArray(new String[vehicleList.size()]);
        vehicleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(array));
    }
    
    private void populateInitPointComboBox() {
        BestPathController bpc = new BestPathController(this.project);
        ArrayList<String> junctionList = bpc.getcomboBoxJunctionList(this.project);
        String[] array = junctionList.toArray(new String[junctionList.size()]);
        initPointComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(array));
    }

    private void populateEndPointComboBox() {
        BestPathController bpc = new BestPathController(this.project);
        ArrayList<String> junctionList = bpc.getcomboBoxJunctionList(this.project);
        String[] array = junctionList.toArray(new String[junctionList.size()]);
        endPointComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(array));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titleLBL = new javax.swing.JLabel();
        sVehicleLBL = new javax.swing.JLabel();
        vehicleComboBox = new javax.swing.JComboBox<>();
        selectInitPointLBL = new javax.swing.JLabel();
        initPointComboBox = new javax.swing.JComboBox<>();
        selectEndPointLBL = new javax.swing.JLabel();
        endPointComboBox = new javax.swing.JComboBox<>();
        fastestBTN = new javax.swing.JButton();
        theoreticalBTN = new javax.swing.JButton();
        realBTN = new javax.swing.JButton();
        resultsLBL = new javax.swing.JLabel();
        resultsPanel = new javax.swing.JPanel();
        pathScroll = new javax.swing.JScrollPane();
        pathTextArea = new javax.swing.JTextArea();
        pathLBL = new javax.swing.JLabel();
        travelingTimeLBL = new javax.swing.JLabel();
        secondsTF = new javax.swing.JTextField();
        consuptionLBL = new javax.swing.JLabel();
        consumptionTF = new javax.swing.JTextField();
        tollLBL = new javax.swing.JLabel();
        tollCostTF = new javax.swing.JTextField();
        exitBTN = new javax.swing.JButton();
        sProjectLBL = new javax.swing.JLabel();
        htmlBTN = new javax.swing.JButton();
        csvBTN = new javax.swing.JButton();
        activeProjectTF = new javax.swing.JTextField();
        dataBaseBTN = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Best Path");
        setMinimumSize(new java.awt.Dimension(605, 742));

        titleLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(0, 102, 153));
        titleLBL.setText(" Best Path");
        titleLBL.setToolTipText("");

        sVehicleLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sVehicleLBL.setForeground(new java.awt.Color(0, 102, 153));
        sVehicleLBL.setText("Select Vehicle:");

        vehicleComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vehicleComboBox.setForeground(new java.awt.Color(102, 102, 102));
        vehicleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[20]));
        vehicleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleComboBoxActionPerformed(evt);
            }
        });

        selectInitPointLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectInitPointLBL.setForeground(new java.awt.Color(0, 102, 153));
        selectInitPointLBL.setText("Select Source:");
        selectInitPointLBL.setToolTipText("");

        initPointComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        initPointComboBox.setForeground(new java.awt.Color(102, 102, 102));
        initPointComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[30]));
        initPointComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initPointComboBoxActionPerformed(evt);
            }
        });

        selectEndPointLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectEndPointLBL.setForeground(new java.awt.Color(0, 102, 153));
        selectEndPointLBL.setText("Select Destiny:");
        selectEndPointLBL.setToolTipText("");

        endPointComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        endPointComboBox.setForeground(new java.awt.Color(102, 102, 102));
        endPointComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[30]));
        endPointComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endPointComboBoxActionPerformed(evt);
            }
        });

        fastestBTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fastestBTN.setForeground(new java.awt.Color(102, 102, 102));
        fastestBTN.setText("Fastest Path");
        fastestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastestBTNActionPerformed(evt);
            }
        });

        theoreticalBTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        theoreticalBTN.setForeground(new java.awt.Color(102, 102, 102));
        theoreticalBTN.setText("Most Efficient Path (Theoretical)");
        theoreticalBTN.setToolTipText("");
        theoreticalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theoreticalBTNActionPerformed(evt);
            }
        });

        realBTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        realBTN.setForeground(new java.awt.Color(102, 102, 102));
        realBTN.setText("Most Efficient Path (Real)");
        realBTN.setToolTipText("");
        realBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realBTNActionPerformed(evt);
            }
        });

        resultsLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultsLBL.setForeground(new java.awt.Color(0, 102, 153));
        resultsLBL.setText("Results");
        resultsLBL.setToolTipText("");

        resultsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        pathScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pathTextArea.setEditable(false);
        pathTextArea.setColumns(20);
        pathTextArea.setForeground(new java.awt.Color(102, 102, 102));
        pathTextArea.setLineWrap(true);
        pathTextArea.setRows(100);
        pathTextArea.setTabSize(20);
        pathTextArea.setToolTipText("");
        pathScroll.setViewportView(pathTextArea);

        pathLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pathLBL.setForeground(new java.awt.Color(0, 102, 153));
        pathLBL.setText("Path");
        pathLBL.setToolTipText("");

        travelingTimeLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        travelingTimeLBL.setForeground(new java.awt.Color(0, 102, 153));
        travelingTimeLBL.setText("Traveling Time(Hours:Minutes:Seconds):");
        travelingTimeLBL.setToolTipText("");

        secondsTF.setEditable(false);
        secondsTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        secondsTF.setForeground(new java.awt.Color(102, 102, 102));
        secondsTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondsTFActionPerformed(evt);
            }
        });

        consuptionLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        consuptionLBL.setForeground(new java.awt.Color(0, 102, 153));
        consuptionLBL.setText("Energy Consumption (MJ):");
        consuptionLBL.setToolTipText("");

        consumptionTF.setEditable(false);
        consumptionTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        consumptionTF.setForeground(new java.awt.Color(102, 102, 102));

        tollLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tollLBL.setForeground(new java.awt.Color(0, 102, 153));
        tollLBL.setText("Total Toll Cost (€): ");
        tollLBL.setToolTipText("");

        tollCostTF.setEditable(false);
        tollCostTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tollCostTF.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout resultsPanelLayout = new javax.swing.GroupLayout(resultsPanel);
        resultsPanel.setLayout(resultsPanelLayout);
        resultsPanelLayout.setHorizontalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsPanelLayout.createSequentialGroup()
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pathScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(pathLBL)))
                .addGap(38, 38, 38)
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tollLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tollCostTF, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addComponent(consuptionLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumptionTF))
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addComponent(travelingTimeLBL)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(secondsTF, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24))
        );
        resultsPanelLayout.setVerticalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsPanelLayout.createSequentialGroup()
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(pathLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pathScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, resultsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(travelingTimeLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consuptionLBL)
                            .addComponent(consumptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tollLBL)
                            .addComponent(tollCostTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exitBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        exitBTN.setForeground(new java.awt.Color(102, 102, 102));
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        sProjectLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sProjectLBL.setForeground(new java.awt.Color(0, 102, 153));
        sProjectLBL.setText("Active Project:");

        htmlBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        htmlBTN.setForeground(new java.awt.Color(102, 102, 102));
        htmlBTN.setText("Save to Html");
        htmlBTN.setToolTipText("");
        htmlBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htmlBTNActionPerformed(evt);
            }
        });

        csvBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        csvBTN.setForeground(new java.awt.Color(102, 102, 102));
        csvBTN.setText("Save to CSV");
        csvBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvBTNActionPerformed(evt);
            }
        });

        activeProjectTF.setEditable(false);
        activeProjectTF.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        activeProjectTF.setForeground(new java.awt.Color(102, 102, 102));
        activeProjectTF.setBorder(null);

        dataBaseBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dataBaseBTN.setForeground(new java.awt.Color(102, 102, 102));
        dataBaseBTN.setText("Save to DataBase");
        dataBaseBTN.setToolTipText("");
        dataBaseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBaseBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectEndPointLBL)
                                    .addComponent(selectInitPointLBL)
                                    .addComponent(sVehicleLBL)
                                    .addComponent(sProjectLBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(endPointComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(initPointComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(activeProjectTF)
                                    .addComponent(vehicleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataBaseBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(csvBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(htmlBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(titleLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(theoreticalBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(realBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fastestBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resultsLBL)
                        .addGap(287, 287, 287))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sProjectLBL)
                    .addComponent(activeProjectTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sVehicleLBL)
                    .addComponent(vehicleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initPointComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectInitPointLBL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endPointComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectEndPointLBL))
                .addGap(18, 18, 18)
                .addComponent(fastestBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(realBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(theoreticalBTN)
                .addGap(18, 18, 18)
                .addComponent(resultsLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(csvBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataBaseBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(htmlBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vehicleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleComboBoxActionPerformed
        BestPathController bpc = new BestPathController(this.project);
        v = this.project.getRegistVehicle().getVehicleByName((String)vehicleComboBox.getSelectedItem());       
    }//GEN-LAST:event_vehicleComboBoxActionPerformed

    private void fastestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastestBTNActionPerformed
        
        pathTextArea.setText("");
        secondsTF.setText("");
        consumptionTF.setText("");
        tollCostTF.setText("");
     
        
        // Using mock objects in RunUI
        BestPathController bpc = new BestPathController(this.project);
        
        double[] values = new double[3];
        values = bpc.getBestPathValues(j1, j2, v, 1.0, 1.0, 1000.0, "FASTESTPATH");
//       v.setLoad(Double.parseDouble(loadTF.getText()));
        //fill fastest pathTextArea
        path = bpc.getBestPathtoArray(j1, j2, v,1.0,1.0,1000.0,"FASTESTPATH");
        for (String name : path) {
            pathTextArea.append(name);
//            if(path.indexOf(name)!=(path.size()-1)){
//                pathTextArea.append("->");
//            }else{
//                pathTextArea.append("; ");
//            }
            
        }
       
        //fill travel time; consumption, tollCost
        secondsTF.setText(RoadNetwork.timeToString(values[0]));
        consumptionTF.setText(Double.toString(values[1]));
        tollCostTF.setText(Double.toString(values[2]));
    }//GEN-LAST:event_fastestBTNActionPerformed

    private void realBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realBTNActionPerformed

        pathTextArea.setText("");
        secondsTF.setText("");
        consumptionTF.setText("");
        tollCostTF.setText("");
       
        
        
        // Using mock objects in RunUI
        BestPathController bpc = new BestPathController(this.project);
        double[] values = new double[3];
        values = bpc.getBestPathValues(j1, j2, v, 1.0, 1.0, load, "EFFECIENTPATHREAL");
        //fill fastest pathTextArea
         path = bpc.getBestPathtoArray(j1, j2, v,1.0,1.0,1000.0,"EFFECIENTPATHREAL");
        for (String name : path) {
            pathTextArea.append(name);
        }
       
        //fill travel time; consumption, tollCost
        secondsTF.setText(RoadNetwork.timeToString(values[0]));
        consumptionTF.setText(Double.toString(values[1]));
        tollCostTF.setText(Double.toString(values[2]));
    }//GEN-LAST:event_realBTNActionPerformed

    private void theoreticalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theoreticalBTNActionPerformed
        
        pathTextArea.setText("");
        secondsTF.setText("");
        consumptionTF.setText("");
        tollCostTF.setText("");
        // Using mock objects in RunUI
        BestPathController bpc = new BestPathController(this.project);
        double[] values = new double[3];
        values = bpc.getBestPathValues(j1, j2, v, 1.0, 1.0, load, "EFFECIENTPATHTHEORICAL");
        //fill fastest pathTextArea
        path = bpc.getBestPathtoArray(j1, j2, v,1.0,1.0,1000.0,"EFFECIENTPATHTHEORICAL");
        for (String name : path) {
            pathTextArea.append(name);
            pathTextArea.append("; ");
        }
       
        //fill travel time; consumption, tollCost
        secondsTF.setText(RoadNetwork.timeToString(values[0]));
        consumptionTF.setText(Double.toString(values[1]));
        tollCostTF.setText(Double.toString(values[2]));
    }//GEN-LAST:event_theoreticalBTNActionPerformed

    private void initPointComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initPointComboBoxActionPerformed
        BestPathController bpc = new BestPathController(this.project);
        j1 = this.project.getJunctionInProject((String) initPointComboBox.getSelectedItem(), this.project.getRoadNetwork().vertices());

    }//GEN-LAST:event_initPointComboBoxActionPerformed

    private void endPointComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endPointComboBoxActionPerformed
        BestPathController bpc = new BestPathController(this.project);
        j2 = this.project.getJunctionInProject((String) endPointComboBox.getSelectedItem(), this.project.getRoadNetwork().vertices());
    }//GEN-LAST:event_endPointComboBoxActionPerformed

    private void csvBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvBTNActionPerformed
        String projName = activeProjectTF.getText();
        String vehicleName = v.getName();
        String initJunctionName = j1.getId();
        String endJunctionName = j2.getId();
        String filePath = "resultsCSV.txt";
        double energyConsumption = Double.parseDouble(consumptionTF.getText());
        double travelTime = Double.parseDouble(secondsTF.getText());
        double tollCost = Double.parseDouble(tollCostTF.getText());

        BestPathController bpc = new BestPathController(this.project);

        bpc.exportNetworkAnalysisCSV(projName, vehicleName, initJunctionName, endJunctionName, energyConsumption,
                travelTime, tollCost, path, filePath);
       
    }//GEN-LAST:event_csvBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        super.dispose();
    }//GEN-LAST:event_exitBTNActionPerformed

    private void htmlBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmlBTNActionPerformed
        String projName = activeProjectTF.getText();
        String vehicleName = v.getName();
        String initJunctionName = j1.getId();
        String endJunctionName = j2.getId();
        String filePath = "resultsHTML.HTML";
        String energyConsumption = consumptionTF.getText();
        String travelTime = secondsTF.getText();
        String tollCost = tollCostTF.getText();

        BestPathController bpc = new BestPathController(this.project);

        bpc.exportNetworkAnalysisHTML(projName, vehicleName, initJunctionName, endJunctionName, energyConsumption,
                travelTime, tollCost, path, filePath);
    }//GEN-LAST:event_htmlBTNActionPerformed

    private void secondsTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondsTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondsTFActionPerformed

    private void dataBaseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBaseBTNActionPerformed
        
        double energyConsumption = Double.parseDouble(consumptionTF.getText());
        String travelTime = secondsTF.getText();
        double tollCost = Double.parseDouble(tollCostTF.getText());
        
        BestPathController bpc = new BestPathController(this.project);
        
        bpc.saveResultsInDataBase(activeProjectTF.getText(), travelTime, energyConsumption, tollCost);
       
    }//GEN-LAST:event_dataBaseBTNActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BestPathUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BestPathUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BestPathUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BestPathUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BestPathUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activeProjectTF;
    private javax.swing.JTextField consumptionTF;
    private javax.swing.JLabel consuptionLBL;
    private javax.swing.JButton csvBTN;
    private javax.swing.JButton dataBaseBTN;
    private javax.swing.JComboBox<String> endPointComboBox;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton fastestBTN;
    private javax.swing.JButton htmlBTN;
    private javax.swing.JComboBox<String> initPointComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pathLBL;
    private javax.swing.JScrollPane pathScroll;
    private javax.swing.JTextArea pathTextArea;
    private javax.swing.JButton realBTN;
    private javax.swing.JLabel resultsLBL;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JLabel sProjectLBL;
    private javax.swing.JLabel sVehicleLBL;
    private javax.swing.JTextField secondsTF;
    private javax.swing.JLabel selectEndPointLBL;
    private javax.swing.JLabel selectInitPointLBL;
    private javax.swing.JButton theoreticalBTN;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JTextField tollCostTF;
    private javax.swing.JLabel tollLBL;
    private javax.swing.JLabel travelingTimeLBL;
    private javax.swing.JComboBox<String> vehicleComboBox;
    // End of variables declaration//GEN-END:variables

    
}
