/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lapr.project.model.Project;
import lapr.project.model.RegistryProject;

/**
 *
 * @author rgcar
 */
public class ChangeProjPropertiesUI extends javax.swing.JFrame {

    public static final long serialVersionUID = 1L;
    //DUMMY OBJECTS TO TEST - from were should i load the list?? file/database
    private RegistryProject rp;
    private Project project;
    private JFrame homeFrame;

    /**
     * Creates new form ChangeProjPropertiesUI
     */
    public ChangeProjPropertiesUI(JFrame homeFrame, RegistryProject rp, Project project) {
        initComponents();
        this.setLocationRelativeTo(null);
        projNameTF.setText(project.getName());
        descriptionTF.setText(project.getDescription());
        this.project = project;
        this.rp = rp;
        this.homeFrame = homeFrame;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projNameLbl = new javax.swing.JLabel();
        projNameTF = new javax.swing.JTextField();
        descriptionLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTF = new javax.swing.JTextArea();
        confirmLbl = new javax.swing.JLabel();
        saveBTN = new javax.swing.JButton();
        confirmLbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        projNameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        projNameLbl.setForeground(new java.awt.Color(102, 102, 102));
        projNameLbl.setText("Project Name:");

        projNameTF.setBackground(new java.awt.Color(204, 204, 204));
        projNameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        projNameTF.setForeground(new java.awt.Color(0, 102, 153));
        projNameTF.setText("Add new project name");
        projNameTF.setBorder(null);
        projNameTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projNameTFMouseClicked(evt);
            }
        });
        projNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projNameTFActionPerformed(evt);
            }
        });

        descriptionLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        descriptionLbl.setForeground(new java.awt.Color(102, 102, 102));
        descriptionLbl.setText("Poject Description:");

        descriptionTF.setBackground(new java.awt.Color(204, 204, 204));
        descriptionTF.setColumns(20);
        descriptionTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descriptionTF.setForeground(new java.awt.Color(0, 102, 153));
        descriptionTF.setRows(5);
        descriptionTF.setText("Add new project description");
        descriptionTF.setBorder(null);
        descriptionTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionTFMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(descriptionTF);

        confirmLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmLbl.setForeground(new java.awt.Color(0, 102, 153));
        confirmLbl.setText("Saved");

        saveBTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveBTN.setForeground(new java.awt.Color(102, 102, 102));
        saveBTN.setText("SAVE");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        confirmLbl1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmLbl1.setForeground(new java.awt.Color(0, 102, 153));
        confirmLbl1.setText(" Error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descriptionLbl)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(confirmLbl))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(confirmLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveBTN, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(projNameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(projNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(projNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(projNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(descriptionLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveBTN)
                .addGap(21, 21, 21))
        );

        confirmLbl.setVisible(false);
        confirmLbl1.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descriptionTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionTFMouseClicked

        //descriptionTF.setText("");
    }//GEN-LAST:event_descriptionTFMouseClicked

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        int n = JOptionPane.showOptionDialog(new JFrame(), "<html>Do you "
                + "want to save changed properties?<br>Titulo:"
                + projNameTF.getText() + "<br>Description:" + descriptionTF.getText() + "</html>",
                "Change Properties", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, new Object[]{"Yes", "No"}, JOptionPane.YES_OPTION);

        if (n == JOptionPane.YES_OPTION) {
            project.setName(projNameTF.getText());
            project.setDescription(descriptionTF.getText());
            MainGUI main = new MainGUI(rp, project);
            homeFrame.dispose();
            this.dispose();
        }


    }//GEN-LAST:event_saveBTNActionPerformed

    private void projNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projNameTFActionPerformed

    private void projNameTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projNameTFMouseClicked

        //projNameTF.setText("");

    }//GEN-LAST:event_projNameTFMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangeProjPropertiesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangeProjPropertiesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangeProjPropertiesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangeProjPropertiesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChangeProjPropertiesUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmLbl;
    private javax.swing.JLabel confirmLbl1;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JTextArea descriptionTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel projNameLbl;
    private javax.swing.JTextField projNameTF;
    private javax.swing.JButton saveBTN;
    // End of variables declaration//GEN-END:variables
}
