/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lapr.project.controller.AddRoadsController;
import lapr.project.controller.AddVehicleController;
import lapr.project.model.Project;
import lapr.project.model.RegistryProject;

/**
 *
 * @author rgcar
 */
public class MainGUI extends javax.swing.JFrame {

    public static final long serialVersionUID = 1L;
    private RegistryProject rp;
    private Project project;

    /**
     * Creates new form CreateProjectGUI
     *
     * @param project
     */
    public MainGUI(RegistryProject rp, Project project) {
        initComponents();
        this.setLocationRelativeTo(null);
        projectNameLbl.setText(project.getName());
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.rp = rp;
        this.project = project;
        setVisible(true);
    }

    public Project getProject() {
        return project;
    }

    private MainGUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel2 = new javax.swing.JLabel();
        projectLbl = new javax.swing.JLabel();
        projectNameLbl = new javax.swing.JLabel();
        changeProjectBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        copy_project = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenuItem();
        addVehiclesFile = new javax.swing.JMenuItem();
        roadConfig = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        bestPath = new javax.swing.JMenuItem();
        vehicleComparison = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/highwaySmall.jpg"))); // NOI18N

        projectLbl.setForeground(new java.awt.Color(153, 153, 153));
        projectLbl.setText("Active Project:");

        projectNameLbl.setForeground(new java.awt.Color(153, 153, 153));

        changeProjectBtn.setForeground(new java.awt.Color(102, 102, 102));
        changeProjectBtn.setText("Change Project");
        changeProjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeProjectBtnActionPerformed(evt);
            }
        });

        jMenuBar1.setPreferredSize(new java.awt.Dimension(170, 40));

        jMenu1.setForeground(new java.awt.Color(102, 102, 102));
        jMenu1.setText("Project");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(85, 24));

        copy_project.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        copy_project.setText("Copy Project");
        copy_project.setPreferredSize(new java.awt.Dimension(141, 40));
        copy_project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copy_projectActionPerformed(evt);
            }
        });
        jMenu1.add(copy_project);

        edit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        edit.setText("Edit Project Properties");
        edit.setPreferredSize(new java.awt.Dimension(293, 40));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jMenu1.add(edit);

        addVehiclesFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        addVehiclesFile.setText("Add Vehicles by file");
        addVehiclesFile.setPreferredSize(new java.awt.Dimension(221, 40));
        addVehiclesFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVehiclesFileActionPerformed(evt);
            }
        });
        jMenu1.add(addVehiclesFile);

        roadConfig.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        roadConfig.setText("Add Road by file");
        roadConfig.setPreferredSize(new java.awt.Dimension(221, 40));
        roadConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roadConfigActionPerformed(evt);
            }
        });
        jMenu1.add(roadConfig);

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        save.setText("Save Project");
        save.setPreferredSize(new java.awt.Dimension(221, 40));
        jMenu1.add(save);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(102, 102, 102));
        jMenu2.setText("Analysis");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(155, 24));

        bestPath.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        bestPath.setText("Best Path");
        bestPath.setPreferredSize(new java.awt.Dimension(107, 40));
        bestPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestPathActionPerformed(evt);
            }
        });
        jMenu2.add(bestPath);

        vehicleComparison.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        vehicleComparison.setText("Veihicle Comparison");
        vehicleComparison.setPreferredSize(new java.awt.Dimension(281, 40));
        vehicleComparison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleComparisonActionPerformed(evt);
            }
        });
        jMenu2.add(vehicleComparison);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(projectLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(projectNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changeProjectBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectNameLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changeProjectBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void copy_projectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copy_projectActionPerformed
        CopyProjectUI copy = new CopyProjectUI(rp, project);
        copy.setVisible(true);
    }//GEN-LAST:event_copy_projectActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        ChangeProjPropertiesUI cpp = new ChangeProjPropertiesUI(this, rp, project);
        cpp.setVisible(true);
    }//GEN-LAST:event_editActionPerformed

    private void addVehiclesFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVehiclesFileActionPerformed
        AddVehicleController addVechicleController = new AddVehicleController(project);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            try {
                boolean result = addVechicleController.importVehiclesData(filePath);
                if (result) {
                    JOptionPane.showMessageDialog(null, "Vehicles added.");
                } else {
                    JOptionPane.showMessageDialog(null, "No new vehicles added.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error Reading File", null, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_addVehiclesFileActionPerformed

    private void changeProjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeProjectBtnActionPerformed
        this.dispose();
        ChooseProjectUI choose = new ChooseProjectUI(rp);
    }//GEN-LAST:event_changeProjectBtnActionPerformed

    private void roadConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roadConfigActionPerformed
        AddRoadsController addRoadsController = new AddRoadsController(project);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            try {
                boolean result = addRoadsController.importRoadsData(filePath);
                if (result) {
                    JOptionPane.showMessageDialog(null, "Roads added.");
                } else {
                    JOptionPane.showMessageDialog(null, "No new roads added.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error Reading File", null, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_roadConfigActionPerformed

    private void bestPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestPathActionPerformed
        BestPathUI bp = new BestPathUI(this.project);
        bp.setVisible(true);
    }//GEN-LAST:event_bestPathActionPerformed

    private void vehicleComparisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleComparisonActionPerformed
        CompareVehiclesUI cv = new CompareVehiclesUI(this.project);
         cv.setVisible(true);
    }//GEN-LAST:event_vehicleComparisonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addVehiclesFile;
    private javax.swing.JMenuItem bestPath;
    private javax.swing.JButton changeProjectBtn;
    private javax.swing.JMenuItem copy_project;
    private javax.swing.JMenuItem edit;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel projectLbl;
    private javax.swing.JLabel projectNameLbl;
    private javax.swing.JMenuItem roadConfig;
    private javax.swing.JMenuItem save;
    private javax.swing.JMenuItem vehicleComparison;
    // End of variables declaration//GEN-END:variables
}
